Minor touch-ups (C++ formatting rules, new machine file)
eagles-project/haero pull request #424
Opened 2022-11-09 22:30 UTC by jeff-cohere

This is just a clean-up PR that switches Haero to LLVM's C++ formatting rules, since that's what we're using for mam4xx, and 1 style is simpler than 2.

@jaelynlitz , I also added your machine file for Deception here. If the hostname matches `deception`, Haero should automatically source this. Let me know if you think it works if you get a chance.

2022-11-09 22:32 UTC, overfelt approved these changes

2022-11-09 22:45 UTC, jaelynlitz commented
Awesome, let me test out the deception set up

2022-11-10 17:32 UTC, jaelynlitz requested changes
Looks good! My only outstanding comment is that for machines that use modules to set up the environment, the config.sh file needs to be sourced instead of ./-ed so that the modules stay loaded so the README should be updated to reflect this

2022-11-10 18:21 UTC, jaelynlitz approved these changes

2022-11-10 18:22 UTC, merged